### ISSUE TITLE
Additional Columns for the payments extract

### ISSUE THREAD

**Issue by richardhartley101** [kin-business/kin.api.public#14]
HTML Link to the Payor user (e.g. https://admin.kin.business/user/5ba3a662a0687536b9256a49) Payor: Name
    Payor: Email (if possible)
    Payor: Card Name (if possible)
    Payor: last 4 digits (if possible)
    Number of cards previously used by the Payor (if possible)
    HTML Link to the Payee user (e.g. https://admin.kin.business/user/5ba3a662a0687536b9256a49) Payee: Name
    Payee: Email
    Payee beneficiary Name: being email (for now)
    Payee Our Reference: to be last 10 digits of our reference (e.g. 00025fd044 )
    Their Reference: "Kin Payment" for now
    For the payee - Number of times This Person with these bank details has been used (we use this to know if we must add the beneficiary and also check for fraud due to over use)

**Comment by rolfwessels** [comment]
@richardhartley101 This is now on develop. Please let me know if it works as expected. 

I was not able to add the following 
* Number of cards previously used by the Payor (if possible)
* Number of times This Person with these bank details has been used

We will need to schedule a bit of time to add this as a feature. Probably best to add a fraud detection module to help deal with these.

**Comment by richardhartley101** [comment]
Hi,

Could you look at these ones
Missing: Payor: Card Name (if possible)
Still Full reference, should just be 10 digits: Payee Our Reference: to be last 10 digits of our reference (e.g. 00025fd044 )
Remove the name, just "Kin Payment": Their Reference: "Kin Payment" for now

**Comment by rolfwessels** [comment]
Done
