### ISSUE TITLE
Bank Failure returns validation error as a success

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#15]
I send an account number which is too long:

{"query":"mutation BankDetailsUpdate($uid: String!, $accountNumber: String!, $sortCodeId: String!, $code: String!) {  bankDetailsUpdate(id: $uid, accountNumber: $accountNumber, sortCodeId: $sortCodeId, code: $code, isDefault: true) {    __typename    id  }}","operationName":"BankDetailsUpdate","variables":{"uid":"5bc071880ff46f0002712c60","accountNumber":"3333555333333336666","sortCodeId":"5bbb071a336f6e0002cc1305","code":"410506"}}

I get a success back like this:
<-- 200 https://api.dev.kin.business/graphql (1767ms)
{"data":{"bankDetailsUpdate":null},"errors":[{"message":"'Account Number' must be between 7 and 16 characters. You entered 19 characters.","path":["sortCodeId","bankDetailsUpdate"],"extensions":{"code":"VALIDATION"}}]}

**Comment by rolfwessels** [comment]
I was about to respond that, that is how GraphQl works but let me go and double check that.

**Comment by JacquesSmuts** [comment]
there was a minor change in how the null response was sent back, but Android has changed its handling of errors and you can close this one.

**Comment by rolfwessels** [comment]
Ok, looks like this is how graphql works.
