### ISSUE TITLE
Deleting a settlement results in inaccurate balances

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#16]
check group with id: 5bc9d6f6eac8140002e8572f

I added on paid transactions, then settled then I was all square.

Then I deleted the settlement and my balance was wrong.

**Comment by rolfwessels** [comment]
Hmmm, that is not good :-)

**Comment by rolfwessels** [comment]
I just wrote a test and it worked as expected. Can you try and reproduce it?

**Comment by rolfwessels** [comment]
Found the issue. Duplicate calls to the remove function would double the remove statistics.

This is now resolved.
