### ISSUE TITLE
User is able to accept an invite that has already been accepted

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#18]
When an invitation is accepted, it does not expire and the server allows more than one acceptance of the same invite.

I would suggest that if an invitation is accepted, the server changes the expiration time to "now()" so that any future views of the invitation is rejected.

**Comment by rolfwessels** [comment]
ok will have a look, thought this was in already.

**Comment by ryanjohndias** [comment]
Could the invitation perhaps not simply tell us expired = true/false, and with a reason?

**Comment by rolfwessels** [comment]
Yup I will add that. Though it will be an expired and reason for signup || add to group. Because we are still using it for both.

**Comment by rolfwessels** [comment]
So I checked the code. It does do a check for usage and wont allow the user to be added. But it does not throw an exeption. I have changed that. It will now throw basic exception.  

Will add the expired reason and outcome to graphql and then deploy.

**Comment by rolfwessels** [comment]
Added flag and simple message.
![image](https://user-images.githubusercontent.com/643179/47655228-3b854580-db95-11e8-927d-64f8614714ff.png)
