### ISSUE TITLE
Accepting Invite does not work

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#2]
I successfully get an invite as follows:

> {"query":"query Invitation($id: String!) {  userInviteByPublicId(id: $id) {    __typename    id    name    expires    invitingUser {      __typename      name    }  }}","operationName":"Invitation","variables":{"id":"**cd2f8fb7afdf4a5996b7988414273fc9**"}}

> {"data":{"userInviteByPublicId":{"__typename":"UserInvite","id":"**5b9637f3e6629d0002784cbc**","name":"joe","expires":"2018-09-17T09:22:59.689+00:00","invitingUser":{"__typename":"ReferenceWithNameType","name":"Bob"}}}}

Then I accept the invitation like so:

> {"query":"mutation AcceptInvitation($id: String!) {  acceptGroupInvite(inviteId: $id) {    __typename    id  }}","operationName":"AcceptInvitation","variables":{"id":"**5b9637f3e6629d0002784cbc**"}}

Which results in an error:

> {"data":{"acceptGroupInvite":null},"errors":[{"message":"GraphQL.ExecutionError: Error trying to resolve acceptGroupInvite. ---> System.AggregateException: One or more errors occurred. (Could not find user invite [**5b9637f3e6629d0002784cbc**].)

Should I be using the publicId instead, and ignore the actual groupInviteId?

**Comment by JacquesSmuts** [comment]
I used the publicId from the invitation deeplink and that works.

**Comment by rolfwessels** [comment]
Cool 👍

**Comment by rolfwessels** [comment]
I can change the input param to say publicInviteId ... to make it clearer?
