### ISSUE TITLE
Balances don't reflect accurate amounts from edited transactions.

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#21]
In group `5bdc496bc67f82000276afec`

it lists the memberToMember balances as:

> Member(uid=5bdc496bc67f82000276afed, name=Jacques Smuts, linked_user_uid=5bbb08d6a0687536b9a92dfc, status=2, image=https://www.gravatar.com/avatar/aee48067a9d435eab1991fec2baece3c.jpg?s=100&d=retro, summary=MemberSummary(balance=R 33.33, totalSpent=R 100, totalIAmOwed=R 100, totalOwe=R 33.33), hasReceivingAccount=false, isCurrentUser=true)

But it should be 
> balance = R0. 
> totalSpent = R100
> totalIAmOwed = R100
> totalOwe = R100

Because there are only two transactions. 
> R100 fully paid by Jacques and split to gh.
> R100 fully paid by ggh and split to Jacques.

As you can see in the transaction records below.

Initially, I split the values evenly, so it shows the R33.33 from those splits. But after editing, the values did not update accurately.

Transaction info below. Please let me know if you need further info.

{"data":{"transactionRecords":[{"__typename":"TransactionRecord","id":"5bdffe84ee1ed50002721fc9","createdByMemberId":"5bbb08d6a0687536b9a92dfc","responsibleMemberId":"5bdc496bc67f82000276afed","type":"Paid","description":"ggh","isInAppSettlement":false,"createDate":"2018-11-05T08:25:40.345+00:00","date":"2018-11-05T10:25:31.772+00:00","updateDate":"2018-11-05T08:55:08.928+00:00","amount":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"plannedAmount":null,"split":{"__typename":"TransactionRecordSplitContext","type":"Ratio","portions":[{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":10000,"currencyIso":"ZAR"},"memberId":"5bdc496bc67f82000276afed","size":0},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"memberId":"5bdffe70afb3060002b5d53a","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"memberId":"5bdffe75afb3060002b5d53d","size":0}]}},{"__typename":"TransactionRecord","id":"5bdffe8fee1ed50002721fcb","createdByMemberId":"5bbb08d6a0687536b9a92dfc","responsibleMemberId":"5bdffe75afb3060002b5d53d","type":"Paid","description":"yyg","isInAppSettlement":false,"createDate":"2018-11-05T08:25:51.327+00:00","date":"2018-11-05T10:25:43.048+00:00","updateDate":"2018-11-05T08:55:19.625+00:00","amount":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"plannedAmount":null,"split":{"__typename":"TransactionRecordSplitContext","type":"Ratio","portions":[{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"memberId":"5bdc496bc67f82000276afed","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"memberId":"5bdffe70afb3060002b5d53a","size":0},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":0,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":10000,"currencyIso":"ZAR"},"memberId":"5bdffe75afb3060002b5d53d","size":0}]}}]}}

**Comment by rolfwessels** [comment]
This is the same issue as before.

![image](https://user-images.githubusercontent.com/643179/48047380-8825dd80-e1a0-11e8-9d9f-84ccaeda06ea.png)

There are duplicate remove requests. I have put a fix in for this but this was broken before that fix.

What this does high-light is that we probably required something that is able to recalculate all balances. Or even beter have a way to detect broken balances.

**Comment by JacquesSmuts** [comment]
If this issue is not yet fixed, shouldn't we keep this ticket open until we have a working solution?

I have a "prevent duplicate API calls" ticket on my end, but until I get to that this issue will persist and I'd like to keep tickets open until we know it's no longer an issue.

Or do you prefer to have this issues list only as a list of things we reported and you looked into?
