### ISSUE TITLE
Some groups don't delete after a success

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#23]
The group remove call was made:

> {"query":"mutation GroupRemove($id: String!) {"GroupRemove","variables":{"id":"5bd977124b558600020cfd50"}}

Followed by a success response from the server:

> {"data":{"groupRemove":{"__typename":"Command","id":"5bd977124b558600020cfd50","command":"GroupRemoveRequest","correlationId":"4f8263a15f7146ab94c6d4ab11538d0d","parameters":null}}}

But when the user queries his groups the group is still there.

**Comment by JacquesSmuts** [comment]
That's the only group we've found that this happens with.

**Comment by rolfwessels** [comment]
Wow that is strange. Will have a look.

**Comment by rolfwessels** [comment]
Ok I found the issue. releasing fix to dev. Please test with that same group and close if it is resolved.

**Comment by rolfwessels** [comment]
Assuming this is fixed.

**Comment by JacquesSmuts** [comment]
Sorry, missed this thread.

Yes it's fixed now. 👍
