### ISSUE TITLE
Some members show hasReceivingAccounts=false incorrectly

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#24]
On the development server in group `5bc70a6e42b5000002b67eba` there is a member `5bc70a7042b5000002b67ebb` with userid=`5bbb08d6a0687536b9a92dfc` which lists `hasReceivingAccount=false` when I do a query for the group.

But when that user does a "me" query, he gets this back, among others.
>{"data":{"me":{"__typename":"User","id":"5bbb08d6a0687536b9a92dfc","email":"smutsaj@gmail.com","hasSignedUp":true,"name":"Jacques Smuts","receivingAccounts":[{"__typename":"UserBankDetail","accountNumber":"3333333333336666","id":"5bc071880ff46f0002712c60","isDefault":true,"sortCode":"410506","sortCodeDetail":{"__typename":"SortCode","id":"5bbb071a336f6e0002cc1305","code":"410506","description":"Bank of Athens"}}]```

Please advise if you need more information

**Comment by JacquesSmuts** [comment]
After updating the bank account info it went to "true".

After our conversation I assume it was fixed and you can close this. :)

**Comment by rolfwessels** [comment]
Ok issue found and fixed.
