### ISSUE TITLE
Balances don't reflect accurate amounts from edited transactions

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#25]
I created a group `5be970090a2e800002e88e7b` and in my logs there are no doubling of API calls and I did not remove any transactions.

I have a group with two members and one transaction.

Then I 
- add a third member, 
- create a second transaction, 
- edit the transaction to change the amount
- edit the transaction to change the split+responsibleId

The balances do not reflect accurately and on my end I cannot find any reason why it should not be accurate.

Can you please check on your end whether or not that group has any double api calls that are not recorded in my logs, or illegal api calls that make it past your validator.

**Comment by rolfwessels** [comment]
Yup there is definitely something wrong with the calculations. I was able to reproduce in my tests. Will fix and let you know. Thanks for the find.

**Comment by rolfwessels** [comment]
Fixed.
