### ISSUE TITLE
Estimate Transactions seems to save wrong responsibleMemberId sometimes?

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#27]
When an Android client updates an Estimate transaction which was created by an iOS client, this happens:

> {"query":"mutation UpdateTransaction($transactionId: String!, $record: TransactionRecordCreateUpdate!) {  transactionRecordUpdate(transactionRecordId: $transactionId, transactionRecord: $record) {    __typename    id  }}","operationName":"UpdateTransaction","variables":{"transactionId":"5bf7ed575f929200021eef6d","record":{"description":"A real estimate","responsibleMemberId":"**5bbb0713a0687536b9a90e59**","transactionType":"Planned","date":"2018-11-23T14:06:36.581+0200","amount":{"currencyIso":"ZAR","cents":-10000}}}}

This returns this issue from the server:

> {"data":{"transactionRecordUpdate":null},"errors":[{"message":"Error trying to resolve transactionRecordUpdate.","locations":[{"line":1,"column":97}],"path":["transactionRecordUpdate"],"extensions":{"code":"REFERENCE_LOOKUP"}}]}

And this is if the estimate was created on Android:

> {"query":"mutation UpdateTransaction($transactionId: String!, $record: TransactionRecordCreateUpdate!) {  transactionRecordUpdate(transactionRecordId: $transactionId, transactionRecord: $record) {    __typename    id  }}","operationName":"UpdateTransaction","variables":{"transactionId":"5bf7ecb1b04cae00028f0cca","record":{"description":"Android estimate","responsibleMemberId":"","transactionType":"Planned","date":"2018-11-23T14:03:54.169+0200","amount":{"currencyIso":"ZAR","cents":-10000},"split":{"type":"Ratio","portions":[]}}}}

The problem here is that on my ui it shows the "paid by" as "not sure yet" because that member ID (**5bf7ed575f929200021eef6d**) cannot be found anywhere, except that we get it from the server as part of the transactionRecord.

This is how Android creates an estimate which is to be paid by not sure yet:

> {"query":"mutation CreateTransaction($groupId: String!, $record: TransactionRecordCreateUpdate!) {  transactionRecordCreate(groupId: $groupId, transactionRecord: $record) {    __typename    id  }}","operationName":"CreateTransaction","variables":{"groupId":"5bbb48bc6130d500022ca7b8","record":{"description":"Hellooo","responsibleMemberId":"","transactionType":"Planned","date":"2018-11-23T15:09:14.599+0200","amount":{"currencyIso":"ZAR","cents":-10000},"split":{"type":"Ratio","portions":[]}}}}

I'm waiting on iOS to send their log, but they indicate that they also send responsibleMemberId as empty string or don't send it.

**Comment by rolfwessels** [comment]
Ok will have a look

**Comment by rolfwessels** [comment]
`"responsibleMemberId":"5bbb0713a0687536b9a90e59"` is not correct because that is not a member Id on the group.

Or what am I missing.

`
5bbb48bc6130d500022ca7b9 Jacques Smuts 
5bbb48c46a0d480002ae4d82 Jannie 
5bbb48d46130d500022ca7ba Ryan 
5bbc96dc48bd920002034062 android 
5bbc97143dea730002fce8e8 chess 
5bbdc3783bb0bc000237bf90 Frikkie 
5bbefefee157e30002189200 Tester 
5bc44160f51dec0002fcac26 new not part 
5bc9a53dd4c7bf0002f8ff45 tester 
5bc9c7eda29fb2000281a913 Man 
5be29fe682028000023a5b53 Alex 
5be92fb2685fec0002a347b3 Alex2.0 
5bf56db60bc95e0002e78181 Bob loblaw 
`

**Comment by JacquesSmuts** [comment]
Yes. The responsibleMemberID is not correct, which is why it fails.

I get that ID from the server and keep it unchanged.

When I search through my logs for "5bbb0713a0687536b9a90e59" I see it only ever appears in the split of that transaction which I get from the server.

**Comment by ryanjohndias** [comment]
Creating an estimate transaction with no responsible member. Sorry for the formatting:

```
Kin.TransactionRecordCreateUpdate(
	“date”: “2018-11-26T09:46:44.414+0200",
 	“amount”: Kin.AmountInput(graphQLMap: [“cents”: -6000), “currencyIso”: “ZAR”)]))),
 	“description”: “IOS TESTER”),
	“split”: Kin.TransactionRecordCreateUpdateSplit(
		[“type”: Kin.SplitType.ratio)), 
		“portions”: [
			Kin.TransactionRecordCreateUpdatePortion(graphQLMap: [“memberId”: “5bf52f0a5b6d9400028bfa2b”), “size”: 1)])), 				
			Kin.TransactionRecordCreateUpdatePortion(graphQLMap: [“memberId”: “5bf52f155b6d9400028bfa36"), “size”: 1)]))
		]))]))),
 	“responsibleMemberId”: nil),
	“transactionType”: Kin.TransactionRecordType.planned))
)
```

**Comment by JacquesSmuts** [comment]
Both iOS and Android had different issues with saving and handling certain states on estimate transactions.

We are sorting out those issues client-side and you can close this ticket.

One thing to note is that you may consider adding a validation check so that an estimate transaction cannot have a split, but that would likely break the iOS build as it currently stands.
