### ISSUE TITLE
First invitation is recorded as "You re-invited"

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#28]
When I add a member for the first time, the activity feed says:
"You added nuMember"

But then when I tap that member for the first time some time later to send them an invite, the activity feed says
"You re-invited nuMember"

**Comment by JacquesSmuts** [comment]
The only time I get "You sent nuMember an invite" is if I add nuMember and do the invitation as part of the add-member flow.

In that case I do not get the "you added nuMember" message. I am guessing that part is by design.

**Comment by rolfwessels** [comment]
That is the design yes. Are you saying its wrong or does not make sense? 

The one that I understand is strange is the "Added" then "Re-invited". I will see if I can keep track of that state to make it a bit clearer.

**Comment by rolfwessels** [comment]
Fixed, will now displaye invited and not re-invited if the member has never been invited.
