### ISSUE TITLE
Incorrect OWE and OWING balances for group

### ISSUE THREAD

**Issue by jannietheron** [kin-business/kin.api.public#3]
When changing a transaction amount, the amount I am owed and amount I am owing is not getting updated.

The balance with the group is correctly calculated.

**Comment by rolfwessels** [comment]
what property are you using ?

**Comment by jannietheron** [comment]
group->member->summary> totalIAmOwed/totalOwe

**Comment by rolfwessels** [comment]
Cool found the issue will fix and let you know.

**Comment by rolfwessels** [comment]
fixed in released 0.0.2.49
