### ISSUE TITLE
Reminder push notification contains "nudge" text (dev server)

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#30]
I presume that the push notifications body text should be updated to reflect the new "reminder" wording. This is how it currently looks:

![IMG_B99DBE516378-1 (1)](https://user-images.githubusercontent.com/6240969/56203187-01293b00-6045-11e9-96f2-43bfb454e1a3.jpeg)

**Comment by rolfwessels** [comment]
I wil confirm but you brought this to my attention before and I believe
Claire said it's correct as it is.

**Comment by rolfwessels** [comment]
This is correct as is.
