### ISSUE TITLE
Ad-hoc group member has incorrect "hasReceivingAccount" status

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#32]
### Preconditions
1. Have a Friend on Kin ("user A") with bank details

### Steps to reproduce
1. Sign in with user B
2. Create a new ad hoc expense
3. Add user A to the expense
4. Make user A the payer
5. Once created, go to Settle
6. "Pay" user A, selecting Pay through Kin (card payment)
7. You're blocked, because you have to request bank details from user A

### Data:
```
groupId
5d304d8f7b49fb0002f8a226

memberId
5c4ac02bc08add0002526630

hasReceivingAccount
false
```

**Comment by rolfwessels** [comment]
👍

**Comment by rolfwessels** [comment]
@ryanjohndias  this should be resolved. Can you please confirm on your side.

**Comment by ryanjohndias** [comment]
Working now, thanks 👍
