### ISSUE TITLE
GroupType property on GroupReference please

### ISSUE THREAD

**Issue by jhavatar** [kin-business/kin.api.public#33]
We need this since the [new share messages](https://trello.com/c/HWi9i9aX/559-share-messages-cleanup) are different depending on if group is adhoc or not. 

New share is fine when in-group sharing since the `type` property exists on the group. BUT, when you have to share (e.g. nudge, pay) from the person balances screen we do not know the GroupType of the ConnectionGroupBalance's GroupReference.

**Comment by ryanjohndias** [comment]
Watching

**Comment by rolfwessels** [comment]
Group reference now has enum property `Type`
