### ISSUE TITLE
Leaving group with active member

### ISSUE THREAD

**Issue by a-bresler** [kin-business/kin.api.public#37]
when I create a group, go into the group and add a FoK, and then leave the group. The group then stays on the group list. When I go into the group, I am no longer on the members list and I can no longer leave the group. Has something perhaps changed on the backend?

**Comment by jacousteau** [comment]
WARN : GraphQl android 2.2.0.dev>requestUserId(5d5ced24e655c1c54810f225)>group: User [Id=5d5ced24e655c1c54810f225 Name=AloXXXX] tried to access group [Group: 5d5d512c9d16a900024eb441 johXXXX] but is not member.

WARN : GraphQl android 2.2.0.dev>requestUserId(5d5ced24e655c1c54810f225)>group: User [Id=5d5ced24e655c1c54810f225 Name=AloXXXX] tried to access group [Group: 5d5d512c9d16a900024eb441 johXXXX] but is not member.

**Comment by rolfwessels** [comment]
Found the issue. Releasing a fix to dev now.

**Comment by rolfwessels** [comment]
@a-bresler  Please test and let me know if the issue persists. Also please close the issue if it was fixed.

**Comment by a-bresler** [comment]
Thanks! Looks good on our side.
