### ISSUE TITLE
Comments Query end cursor not working as expected.

### ISSUE THREAD

**Issue by JavonneM** [kin-business/kin.api.public#38]
Let's say I make the comments query call and `hasNextPage = false` and I store the `endCursor` for subsequent use. If i then add a comment and use the stored `endCursor` in a subsequent call,  I get no data, the only thing that I can see that has changed is the count. 

An example situation, The first call uses `first: 20` with `endCursor: null` but I only had 10 comments to begin with, so the first call returned the 10 items with `hasNextPage = false` and stored the `endCursor` for the next use, I then added a comment, i then used the `endCursor` and got nothing back. If I do the call without `endCursor` i get the 11 items.

**Comment by rolfwessels** [comment]
Could not replicate the issue.
Get my groups and transactions
```graphql
groupsQuery {
     items {
      id,
      name
      transactions {id}
     }
   }
```
Run the delta call and get empty item list
```graphql
  commentQuery(attachmentType:TRANSACTION, batchId: "5d15cc6b8a027100027ff048" orderBy:"Delta" ) {
    
    items {
      id 
      message
    }
    endCursor
    hasNextPage
    count
  }
```

Create a comment
```graphql

mutation {
  commentCreate(
    comment: {
      attachmentType: TRANSACTION
      attachedToId: "5d1c6f1dc7ef5e0002bf2bc4"
      batchId: "5d15cc6b8a027100027ff048"
      message: "Comment 1"
    }
  ) {
    id
  }
}
```
Run query again with after param and it works returns the result. If I update the after to the new endCursor then it has no results.

```graphql
commentQuery(attachmentType:TRANSACTION, batchId: "5d15cc6b8a027100027ff048" orderBy:"Delta" after:"2019-08-27T10:18:44.8630000Z--5d6503847244c2000245dcda") {
    
    items {
      id 
      message
    }
    endCursor
    hasNextPage
    count
  }
```

**Comment by rolfwessels** [comment]
Closing
