### ISSUE TITLE
Default group image shown on activity feed before image upload happens

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#41]
![Screenshot 2019-09-10 at 11 48 15](https://user-images.githubusercontent.com/6240969/64603933-749b6280-d3c1-11e9-82c5-3705c9eee69c.png)

Not sure if this is a big enough deal to change anything

The events for group creation will show the default group image, since they would have been created before the image upload. If it is a problem, could we have the group images default to null image instead?

**Comment by rolfwessels** [comment]
Interesting, that is more a delta issue :-/ ehmm will talk to Claire about it

**Comment by rolfwessels** [comment]
We need to discuss this. Can we please have a call @ryanjohndias  & @jh ?
