### ISSUE TITLE
New FROM email address for Sign in emails

### ISSUE THREAD

**Issue by AndreHelpkin** [kin-business/kin.api.public#43]
Currently, our Sign In magic link emails come from no reply@thekinapp.com

With the change over to our nee kin.me domain, is it possible that we can send these from 
 noreply@kin.me

![image](https://user-images.githubusercontent.com/55178469/64674004-f649c980-d46f-11e9-8668-c0c6db6f3189.png)

**Comment by rolfwessels** [comment]
Will have a look 👍

**Comment by rolfwessels** [comment]
Resolved. Should now be from noreply@kin.me
