### ISSUE TITLE
activityFeedMarkAsSeen does not mark all activities as seen

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#45]
Testing in Playground:

```
mutation {
    activityFeedMarkAsSeen(groupId: null, cursor: null) {
        id
    }
}
```

then 

```
query UserActivities($first: Int, $after: String, $orderBy: String) {
	userActivitiesQuery(first: $first, after: $after, orderBy: $orderBy) {
    items { 
      seen
    }
  }
}
```

result (snippet):

```
{
  "data": {
    "userActivitiesQuery": {
      "items": [
        {
          "seen": true
        },
        {
          "seen": true
        },
        {
          "seen": false
        },
        {
          "seen": true
        },
```

Interestingly, the UI seems to indicate that `activityFeedMarkAsSeen` has only applied to activities that in a sense related to you (observe the bold vs unbold items):

![Screenshot 2019-09-12 at 08 38 54](https://user-images.githubusercontent.com/6240969/64759935-c6b2c400-d538-11e9-82c2-751e87cffca2.png)
![Screenshot 2019-09-12 at 08 38 45](https://user-images.githubusercontent.com/6240969/64759937-c6b2c400-d538-11e9-86a4-2561defac27c.png)

**Comment by rolfwessels** [comment]
Found the issue. Releasing new version now.

**Comment by rolfwessels** [comment]
Resolved and deployed. Please test and close.
