### ISSUE TITLE
Can't create a new ghost in an adhoc group

### ISSUE THREAD

**Issue by JavonneM** [kin-business/kin.api.public#46]
When creating a new ghost group member using the `groupAddMember` mutation in an adhoc group, the call fails with a duplicate friendId validation error: 
`WARN : GraphQl ios 2.6.1.development>requestUserId(5da6bc04dc2113a2f658316b)>groupAddMember: Validation failed: 
-- Members: Members cannot contain duplicate friend ids.` 

Note the call only has the following parameters
name, groupId, email, phoneNumber, contactUUID

**Comment by rolfwessels** [comment]
I found the issue. The fix is in a PR will let you know when it is released.

**Comment by rolfwessels** [comment]
Sorry it took a bit longer to fix than expected. Had some knock on bugs. Should all be sorted in dev now.
