### ISSUE TITLE
When settling, memberToMemberBalances don't update

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#5]
I have this group:

> {
	"data": {
		"group": {
			"__typename": "Group",
			"createDate": "2018-09-11T12:05:51.015+00:00",
			"id": "5b97af9e3157ef0002c8b1fd",
			"name": "jjjj",
			"updateDate": "2018-09-11T12:58:17.592+00:00",
			"summary": {
				"__typename": "GroupSummary",
				"totalSpent": {
					"__typename": "Amount",
					"cents": 17260,
					"currencyIso": "ZAR"
				},
				"totalEstimate": {
					"__typename": "Amount",
					"cents": 0,
					"currencyIso": "ZAR"
				}
			},
			"memberToMemberBalance": [{
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97afa8c93c690002aef190",
				"toMemberId": "5b97af9f3157ef0002c8b1fe",
				"amount": {
					"__typename": "Amount",
					"cents": 3096,
					"currencyIso": "ZAR"
				}
			}, {
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97af9f3157ef0002c8b1fe",
				"toMemberId": "5b97b81b95c71b000231a76f",
				"amount": {
					"__typename": "Amount",
					"cents": 2467,
					"currencyIso": "ZAR"
				}
			}, {
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97afa8c93c690002aef190",
				"toMemberId": "5b97b81b95c71b000231a76f",
				"amount": {
					"__typename": "Amount",
					"cents": **3333**,
					"currencyIso": "ZAR"
				}
			}],
			"members": [{
				"__typename": "GroupMember",
				"id": "5b97af9f3157ef0002c8b1fe",
				"image": "https://www.gravatar.com/avatar/aee48067a9d435eab1991fec2baece3c.jpg?s=100&d=retro",
				"name": "Jacques",
				"status": "Active",
				"userId": "5b961d1da266eb0002efe61b",
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": 629,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 7260,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 8961,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 8332,
						"currencyIso": "ZAR"
					}
				}
			}, {
				"__typename": "GroupMember",
				"id": "5b97afa8c93c690002aef190",
				"image": "https://www.gravatar.com/avatar/495e807e18982c28abad30f952b40914.jpg?s=100&d=retro",
				"name": "hdhdh",
				"status": "Invited",
				"userId": null,
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": -6429,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 0,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 4166,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 10595,
						"currencyIso": "ZAR"
					}
				}
			}, {
				"__typename": "GroupMember",
				"id": "5b97b81b95c71b000231a76f",
				"image": "https://www.gravatar.com/avatar/2ccec9cad37a7527c36ddb7ad485af02.jpg?s=100&d=retro",
				"name": "jangesig",
				"status": "Active",
				"userId": "5b8cf6ef4203140002f4036b",
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": 5800,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 10000,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 14165,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 8365,
						"currencyIso": "ZAR"
					}
				}
			}]
		}
	}
}

### I owe one member **3333** cents, so then I make a settlement like so:

> "query":"mutation CreateSettlement($groupId: String!, $settlement: TransactionRecordSettlement!) {  transactionRecordCreateSettlement(groupId: $groupId, settlement: $settlement) {    __typename    id  }}","operationName":"CreateSettlement","variables":{"groupId":"5b97af9e3157ef0002c8b1fd","settlement":{"description":"nothing","fromMemberId":"5b97af9f3157ef0002c8b1fe","date":"2018-09-11T15:13:26.533","to":[{"memberId":"5b97b81b95c71b000231a76f","amount":{"currencyIso":"ZAR","cents":3333}}]}}}

With success from the server

But then when the group updates I get this response:

> {
	"data": {
		"group": {
			"__typename": "Group",
			"createDate": "2018-09-11T12:05:51.015+00:00",
			"id": "5b97af9e3157ef0002c8b1fd",
			"name": "jjjj",
			"updateDate": "2018-09-11T13:13:27.752+00:00",
			"summary": {
				"__typename": "GroupSummary",
				"totalSpent": {
					"__typename": "Amount",
					"cents": 17260,
					"currencyIso": "ZAR"
				},
				"totalEstimate": {
					"__typename": "Amount",
					"cents": 0,
					"currencyIso": "ZAR"
				}
			},
			"memberToMemberBalance": [{
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97afa8c93c690002aef190",
				"toMemberId": "5b97af9f3157ef0002c8b1fe",
				"amount": {
					"__typename": "Amount",
					"cents": 3096,
					"currencyIso": "ZAR"
				}
			}, {
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97b81b95c71b000231a76f",
				"toMemberId": "5b97af9f3157ef0002c8b1fe",
				"amount": {
					"__typename": "Amount",
					"cents": 866,
					"currencyIso": "ZAR"
				}
			}, {
				"__typename": "GroupMemberToPayMember",
				"fromMemberId": "5b97afa8c93c690002aef190",
				"toMemberId": "5b97b81b95c71b000231a76f",
				"amount": {
					"__typename": "Amount",
					"cents": **3333**,
					"currencyIso": "ZAR"
				}
			}],
			"members": [{
				"__typename": "GroupMember",
				"id": "5b97af9f3157ef0002c8b1fe",
				"image": "https://www.gravatar.com/avatar/aee48067a9d435eab1991fec2baece3c.jpg?s=100&d=retro",
				"name": "Jacques",
				"status": "Active",
				"userId": "5b961d1da266eb0002efe61b",
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": 3962,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 10593,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 12294,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 8332,
						"currencyIso": "ZAR"
					}
				}
			}, {
				"__typename": "GroupMember",
				"id": "5b97afa8c93c690002aef190",
				"image": "https://www.gravatar.com/avatar/495e807e18982c28abad30f952b40914.jpg?s=100&d=retro",
				"name": "hdhdh",
				"status": "Invited",
				"userId": null,
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": -6429,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 0,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 4166,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 10595,
						"currencyIso": "ZAR"
					}
				}
			}, {
				"__typename": "GroupMember",
				"id": "5b97b81b95c71b000231a76f",
				"image": "https://www.gravatar.com/avatar/2ccec9cad37a7527c36ddb7ad485af02.jpg?s=100&d=retro",
				"name": "jangesig",
				"status": "Active",
				"userId": "5b8cf6ef4203140002f4036b",
				"summary": {
					"__typename": "GroupMemberSummary",
					"balance": {
						"__typename": "Amount",
						"cents": 2467,
						"currencyIso": "ZAR"
					},
					"totalSpent": {
						"__typename": "Amount",
						"cents": 10000,
						"currencyIso": "ZAR"
					},
					"totalIAmOwed": {
						"__typename": "Amount",
						"cents": 14165,
						"currencyIso": "ZAR"
					},
					"totalOwe": {
						"__typename": "Amount",
						"cents": 11698,
						"currencyIso": "ZAR"
					}
				}
			}]
		}
	}
}

Am I reading the data correctly?

**Comment by rolfwessels** [comment]
Wow, that is hard to read. I cant look at it today but will get back to you after I figure out what you are trying to do.

**Comment by JacquesSmuts** [comment]
Is there a better way to format the data for github issues? Github steals formatting away for some reason -_-

For now, Ctrl+F 3333 and look for the bolded parts and you'll get an idea. It looks from my side as if settlements don't work.

**Comment by JacquesSmuts** [comment]
This issue was fixed by going over to the summary with memberbalances that are now accurately reflected in the group, from Jannie's issue.
