### ISSUE TITLE
Suggestions: Improving sign-up error handling

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#51]
While testing a certain flow/bug, I came across the following scenario:

When signing up with an invite link to group:

1. If the invite ID that's passed along on the `signUpAuthenticatedUser` call doesn't exist or is broken, then we receive an error, and the user is blocked from continuing. The signup still succeeds on the backend
Suggestion a) Make this a silent fail - so that the user can still proceed?
Suggestion b) Return a specific `errorKey` in the error so that we can allow the user through

The above is based on the assumption that we don't want to block the user.

2. If scenario (1) happens, then if the user tries again, they get the following error: (altered for readability)
```
        - key : "extensions"
            - key : code
            - value : VALIDATION
[...]
        - key : "path" : signUpAuthenticatedUser
        - key : "message" : User Id=5dcbc7bc7878f116af5201e1 Name=333XXXX has already signed up.
```
Suggestion a) Return a specific `errorKey` in the error so that we can allow the user to proceed if they are already signed up for whatever reason

**Comment by rolfwessels** [comment]
We have had 6 instances of this happening in the last 3 months. Is it a caching issue. ? Why do we allow people to sign up again?

I can do suggestion B. will do it and let you know

**Comment by rolfwessels** [comment]
Found the root of the problem being - invites not generated. 

Will monitor and open up again if this issue continues after this release.
