### ISSUE TITLE
No member added when (successfully?) adding friend to group

### ISSUE THREAD

**Issue by jhavatar** [kin-business/kin.api.public#52]
Adding friend with call:
```{"operationName":"AddMemberFromFriends","variables":{"groupId":"5de4fb6e2571cb00017ff329","friendId":"5dd7d1c25087d000011a2eba"},"query":"mutation AddMemberFromFriends($groupId: String!, $friendId: String!) {  groupAddMemberFromFriends(groupId: $groupId, friendId: $friendId) {    __typename    ...commandData  }}fragment commandData on Command {  __typename  id  command  correlationId  parameters {    __typename    key    value  }}"}```

Got server response:
```{"data":{"groupAddMemberFromFriends":{"__typename":"Command","id":"5de517ee46689e0001dfa83c","command":"GroupInviteMemberRequest","correlationId":"18f14ecfbab544d79aac30da7fda1fe3","parameters":null}}}```

Response looks like success but afterwards no new member on group and no member of group matches friend's connectionId, i.e.
```group.members.find { it.connectionId == friend.connectionId }``` is null

**Comment by rolfwessels** [comment]
Should be fixed. let me know if still not fixed.
