### ISSUE TITLE
Group member and Connection status don't match up

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#53]
We're having the following issue: When adding and inviting a contact from the group context (calls GroupAddMember and then GroupInviteExistingMember ), the resulting connection's status remains .notInvited , where the group.member is .invited. 

https://kin-money.slack.com/archives/CC1JM6PPB/p1575364934022400

**Comment by rolfwessels** [comment]
Think we are going to leave it as is for now. Group invites and connection invites should be tracked separately.
