### ISSUE TITLE
If responsibleMemberID has ratio split of 0, overflow amount is incorrectly assigned to that member.

### ISSUE THREAD

**Issue by JacquesSmuts** [kin-business/kin.api.public#7]
I do the mutation to split R100 between all members (except myself).

{"query":"mutation UpdateTransaction($transactionId: String!, $record: TransactionRecordCreateUpdate!) {  transactionRecordUpdate(transactionRecordId: $transactionId, transactionRecord: $record) {    __typename    id  }}","operationName":"UpdateTransaction","variables":{"transactionId":"5ba3b7364f67f300020ec90f","record":{"description":"inequel","responsibleMemberId":"5ba3b6e6c0e6830002b5365c","transactionType":"Paid","date":"2018-09-20T17:05:09.715","amount":{"currencyIso":"ZAR","cents":-10000},"split":{"type":"Ratio","portions":[{"memberId":"**5ba3b6e6c0e6830002b5365c**","size":**0**},{"memberId":"5ba3b6ecc0e6830002b5365f","size":1},{"memberId":"5ba3b6f2c0e6830002b53660","size":1},{"memberId":"5ba3b6fb4f67f300020ec909","size":1},{"memberId":"5ba3b7004f67f300020ec90a","size":1},{"memberId":"5ba3b70f4f67f300020ec90b","size":1},{"memberId":"5ba3b7164f67f300020ec90c","size":1}]}}}}

But then when I get the transaction back in the query, memberid *5ba3b6e6c0e6830002b5365c* with size=0 has been given money, like this:

{"data":{"transactionRecords":[{"__typename":"TransactionRecord","id":"5ba3b7364f67f300020ec90f","createdByMemberId":"5b9928abb814d80002f225d8","responsibleMemberId":"5ba3b6e6c0e6830002b5365c","type":"Paid","description":"inequel","createDate":"2018-09-20T15:05:26.06+00:00","date":"2018-09-20T17:05:09.715+00:00","updateDate":"2018-09-20T15:05:47.164+00:00","amount":{"__typename":"Amount","cents":-10000,"currencyIso":"ZAR"},"plannedAmount":null,"split":{"__typename":"TransactionRecordSplitContext","type":"Ratio","portions":[{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","**cents**":**-4**,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":9996,"currencyIso":"ZAR"},"memberId":"5ba3b6e6c0e6830002b5365c","size":0},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b6ecc0e6830002b5365f","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b6f2c0e6830002b53660","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b6fb4f67f300020ec909","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b7004f67f300020ec90a","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b70f4f67f300020ec90b","size":1},{"__typename":"TransactionRecordPortion","amount":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"responsible":{"__typename":"Amount","cents":-1666,"currencyIso":"ZAR"},"memberId":"5ba3b7164f67f300020ec90c","size":1}]}}]}}

Is my client interpreting the data incorrectly, or does this data indicate that 4 cents goes towards the responsibleMemberID, when it should be 0 cents?

**Comment by rolfwessels** [comment]
Nice find, I will look into it tomorrow 👍

**Comment by rolfwessels** [comment]
Fixed. Will update now
