### ISSUE TITLE
Duplicate sortCodes on dev

### ISSUE THREAD

**Issue by ryanjohndias** [kin-business/kin.api.public#8]
```
query Banks {
  sortCodes {id, description }
}

{
  "data": {
    "sortCodes": [
      {
        "id": "5badd99d151cc40002df980e",
        "description": "ABSA Bank"
      },
........
      {
        "id": "5badd99d151cc40002df981a",
        "description": "ABSA Bank"
      },
........
    ]
  }
}
```

**Comment by kinggs** [comment]
I have a theory. Will have to check with Rolf before we close the issue. But the two sets were created within milliseconds of each other. This makes me think it might be that the initial population was triggered in parallel. 

I *think* it was triggered from /admin/api/ping

{"_id":"5badd99d151cc40002df980e","Cd":"2018-09-28T07:34:53.548Z","Ud":"2018-09-28T07:34:53.548Z","Description":"ABSA Bank","Code":"632005"}

{"_id":"5badd99d151cc40002df981a","Cd":"2018-09-28T07:34:53.562Z","Ud":"2018-09-28T07:34:53.562Z","Description":"ABSA Bank","Code":"632005"}

**Comment by kinggs** [comment]
The problem now is that we have both instances used in TransactionInAppSettlement. Will have to work out a tricky migration for this...

Leaving the queries here for future reference: 

```js
// 562
{Cd: new Date('2018-09-28 09:34:53.562')}
{"ToMembers": {$elemMatch: {"BankDetail.SortCodeId": {$in: [
    '5badd99d151cc40002df981a',
    '5badd99d151cc40002df981b',
    '5badd99d151cc40002df981c',
    '5badd99d151cc40002df981d',
    '5badd99d151cc40002df981e',
    '5badd99d151cc40002df981f',
    '5badd99d151cc40002df9820',
    '5badd99d151cc40002df9821',
    '5badd99d151cc40002df9822',
    '5badd99d151cc40002df9823',
    '5badd99d151cc40002df9824',
    '5badd99d151cc40002df9825'
    ]}}}}

// 548
{Cd: new Date('2018-09-28 09:34:53.548')}
{"ToMembers": {$elemMatch: {"BankDetail.SortCodeId": {$in: [
    '5badd99d151cc40002df980e',
    '5badd99d151cc40002df980f',
    '5badd99d151cc40002df9810',
    '5badd99d151cc40002df9811',
    '5badd99d151cc40002df9812',
    '5badd99d151cc40002df9813',
    '5badd99d151cc40002df9814',
    '5badd99d151cc40002df9815',
    '5badd99d151cc40002df9816',
    '5badd99d151cc40002df9817',
    '5badd99d151cc40002df9818',
    '5badd99d151cc40002df9819'
    ]}}}}
```

**Comment by rolfwessels** [comment]
Yes it looks like my migration script ran twice. Its very rudimentary and I did not add any locking. I can fix these but since they are only on dev I would rather spend time on improving the locking system around migrations.

**Comment by rolfwessels** [comment]
Resolved the issue. Should not happen again.
