### ISSUE TITLE
Estimate totals wrong

### ISSUE THREAD

**Issue by jannietheron** [kin-business/kin.api.public#9]
The capturing person seems to influence estimates negative/positive value

Attached are screenshots of iOS and Android with one estimate added on each side

* Note iOS is removing the "-" in the list

![screenshot_20181005-141403](https://user-images.githubusercontent.com/16534981/46534898-01809680-c8aa-11e8-92a9-66b0e939c8c1.jpg)
![img_0100](https://user-images.githubusercontent.com/16534981/46534922-13fad000-c8aa-11e8-8050-cb329e4a935b.PNG)

**Comment by jannietheron** [comment]
We are displaying group.summary.totalEstimate.cents from the backend

**Comment by rolfwessels** [comment]
Ok I will have a look. That does not make sense.

**Comment by rolfwessels** [comment]
Android passing possitive values in amount.
